### ISSUE TITLE
Fields change when I add a withdrawal strategy

### ISSUE THREAD

**Issue by bsparson** [gasserma/dwr#12]
I figured out why eventually but it was confusing for a while. It was not clear that adding multiple "withdrawal strategies" on the same "strategy" would pull money from the same pot. 

Then when I figured it out I was sad I could only compare 2.

**Comment by gasserma** [comment]
I'm going to fold this into the "create an intro/tutorial/explain it like im five" page. We can talk about the choice to only allow pairwise comparisons. Its definitely feature work at this point. I went from 1 to 2, not from 1 to n with respect to how the front end code is written. I justified it by claiming that more than 2 would be too cluttered in the UI.
