### ISSUE TITLE
Doesn't work on iPhone 6s in Safari

### ISSUE THREAD

**Issue by mrtalberto** [gasserma/dwr#5]
Site loads. Menu works. Text boxes for entering values seem to work.

The add new strategy button causes nothing to change about the site. No scrolling in any direction gets me any strategy to edit.

The FAQ and About pages have crazy margins. My screen is essentially split into three equal size columns with text in the middle one.

I'll try to attach screenshots later.

**Comment by gasserma** [comment]
Thanks! I'll have to figure out how to repro stuff like this... I imagine I know what the issue is on the margins, so don't worry about screenshots. The add strategy button one though, I'm not sure.

**Comment by gasserma** [comment]
I fixed the margins issue. Are there any obvious debugging options on the phone browser for the add strategy button? It doesn't seem straightforward for me to find an iphone or emulator right now.

**Comment by gasserma** [comment]
85% sure I fixed the add strategy button issue. I have no way of testing though...
