### ISSUE TITLE
No dots on graph

### ISSUE THREAD

**Issue by bsparson** [gasserma/dwr#7]
Bad graph on:
Chrome:
Version 57.0.2987.133 (64-bit)
Mac: 
10.11.6

Works on my Amazon fire phone though, as well as Safari 10.1

**Comment by gasserma** [comment]
That is my exact version of chrome. I think what happened is likely some server side error or intermittency you hit that silently failed. I've seen this happen too when it can't get the d3 javascript library from the cdn. Can you try to repro it? And if it repros can you open the debugger and see if there is any obvious error output?

**Comment by bsparson** [comment]
what does it mean to repro it?

Ben Parsons

**Comment by gasserma** [comment]
Reproduce, aka try again with the same preconditions that lead to the bug.

**Comment by gasserma** [comment]
Just got an email from bsparson that this isn't reproing.
