### ISSUE TITLE
Old data

### ISSUE THREAD

**Issue by bsparson** [gasserma/dwr#8]
You might not want to use the older data by default. In most financial data analysis the convention is to only use data newer than 1960 or 1970 if I remember right. You want avoid the depression, war and post-war effects on the economy since they are anomalies, and would lead to poor predictions for the future. It is interesting to see on your graphs, but I think it leads to aggregate stats that are not as useful.

These are the 3 main papers I had saved about portfolio optimization, while that is different than what you are doing I think reasons for using these data ranges are the same.

[Portfolio Selection with Parameter and Model Uncertainty
](http://www.ucd.ie/t4cms/UPPAL.pdf)
This uses 1970 and later

[A Generalized Approach to Portfolio Optimization
](http://faculty.london.edu/avmiguel/DeMiguelGarlappiNogalesUppalMS.pdf)
1963 and later

[Optimal Versus Naive Diversification: How Inefficient is the 1/N Portfolio Strategy?
](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=1376199)
1963 and later

**Comment by gasserma** [comment]
Well, I have read at least the abstracts of all those. They all seem concerned with divining the covariance between stock and bond returns such that they can help you plan portfolio allocations. Weirdly none of the strategies I have implemented change the allocation through time. I am considering making that a first class thing (ie provide some ramp options for changing from stocks to bonds).

That all said, I agree that during WWII and the great depression stocks and bonds had a weird relationship. But I don't think that the market on the whole was an outlier, which is more what this is concerned with.

On top of that, I am attempting to duplicate exactly this: https://www.onefpa.org/journal/Pages/Portfolio%20Success%20Rates%20Where%20to%20Draw%20the%20Line.aspx

The default values and conventions generally match up to that paper. I think it is (or really their initial paper, I cited the follow up that just added a few years of data) the broadest paper as far as impact in this space.

So... I'm going to put year inputs near the top of my additional features work, such that you can enter beginning and end year for the backtesting.
